// Generated by tools/sync-game-tables.mjs from src/data. Do not edit by hand.
export const SYMBOL_IDS = ["page","book","globe","quill","star","wiki","wild","bonus"];
export const REEL: string[] = ["page","page","page","page","page","page","page","page","page","page","book","book","book","book","book","book","book","globe","globe","globe","globe","globe","bonus","quill","quill","quill","quill","star","star","wiki","wild","bonus"];
export const PAYLINES: { id: string; rows: number[] }[] = [{"id":"top","rows":[0,0,0]},{"id":"middle","rows":[1,1,1]},{"id":"bottom","rows":[2,2,2]},{"id":"down","rows":[0,1,2]},{"id":"up","rows":[2,1,0]}];
export const PAYTABLE: Record<string, Record<number, number>> = {"page":{"2":0.5,"3":3.5},"book":{"2":1,"3":8},"globe":{"2":2,"3":16},"quill":{"2":3,"3":32},"star":{"2":5,"3":100},"wiki":{"2":6,"3":350},"wild":{"2":9,"3":700}};
export const LINE_BETS = [2,5,10,25,50];
export const WILD = "wild";
export const SCATTER = "bonus";
export const SCATTER_MIN = 3;
export const BONUS_SPINS = 8;
